# Generated by Django 5.2.7 on 2025-11-02 20:45

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=128, region='BR')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=128, region='BR', verbose_name='Telefone')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='É whatsapp?')),
                ('observacoes', models.TextField(default='Nenhuma', verbose_name='Observações')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSistema', models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End'), ('Mobile', 'Mobile'), ('Projeto de Bi', 'Projeto de Bi'), ('Sistemas Embarcados', 'Sistemas Embarcados'), ('Cloud', 'Cloud')], default='Front-End', max_length=50, verbose_name='Tipo do Sistema')),
                ('nomeSolucao', models.CharField(max_length=100, verbose_name='Nome da Solução')),
                ('objetivo', models.TextField()),
                ('tecnologias', models.TextField()),
                ('representante', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=15, region='BR')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='É whatsapp?')),
                ('expectativa', models.CharField(choices=[('6 meses', '6 meses'), ('9 meses', '9 meses'), ('1 ano', '1 ano'), ('Não tenho expectativa', 'sem expectativa')], default='6 meses', max_length=21)),
                ('vinculoIbmec', models.CharField(choices=[('Aluno / Ex-aluno IBMEC', 'Aluno / Ex-aluno IBMEC'), ('faço parte do IBMEC HUBS', 'faço parte do IBMEC HUBS'), ('Não tenho vínculo com o IBMEC', 'Não tenho vínculo com o IBMEC')], default='Não tenho vínculo com o IBMEC', max_length=100, verbose_name='Possui vínculo com o IBMEC?')),
                ('situação', models.CharField(choices=[('Em análise', 'Em análise'), ('Recusada', 'Recusada'), ('Aprovada', 'Aprovada')], default='Em análise', max_length=20)),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Em andamento', max_length=50)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('coordenador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.coordenador')),
                ('professor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.professor')),
                ('proposta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.proposta')),
            ],
        ),
    ]
