# Generated by Django 5.2.7 on 2025-10-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='titulo',
            new_name='nomeSolucao',
        ),
        migrations.RenameField(
            model_name='proposta',
            old_name='resumo',
            new_name='tecnologias',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='duracao',
        ),
    ]
