# Generated by Django 5.2.7 on 2025-10-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_titulo_proposta_nomesolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='publicoAlvo',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='recursosNecessarios',
        ),
        migrations.AddField(
            model_name='proposta',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proposta',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='expectativa',
            field=models.CharField(choices=[('6 meses', '6 meses'), ('9 meses', '9 meses'), ('1 ano', '1 ano'), ('Não tenho expectativa', 'sem expectativa')], default='6 meses', max_length=21),
        ),
        migrations.AddField(
            model_name='proposta',
            name='representante',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proposta',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='proposta',
            name='tipoSistema',
            field=models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End'), ('Mobile', 'Mobile'), ('Projeto de Bi', 'Projeto de Bi'), ('Sistemas Embarcados', 'Sistemas Embarcados'), ('Cloud', 'Cloud')], default='Front-End', max_length=50, verbose_name='Tipo do Sistema'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='vinculoIbmec',
            field=models.CharField(choices=[('Aluno / Ex-aluno IBMEC', 'Aluno / Ex-aluno IBMEC'), ('Faço / faço parte do IBMEC HUBS', 'Faço / faço parte do IBMEC HUBS'), ('Índio não ter vínculo com IBMEC', 'Índio não ter vínculo com IBMEC')], default='Índio não ter vínculo com IBMEC', max_length=100, verbose_name='Possui vínculo com o IBMEC?'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='É whatsapp?'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='nomeSolucao',
            field=models.CharField(max_length=100, verbose_name='Nome da Solução'),
        ),
    ]
