# Generated by Django 5.2.7 on 2025-11-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_proposta_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AddField(
            model_name='projeto',
            name='grupoAlunos',
            field=models.TextField(blank=True, verbose_name='cadastro.Aluno'),
        ),
    ]
