# Generated by Django 5.2.7 on 2025-10-31 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_proposta_publicoalvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='coordenador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.coordenador'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.professor'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='representante',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='vinculoIbmec',
            field=models.CharField(choices=[('Aluno / Ex-aluno IBMEC', 'Aluno / Ex-aluno IBMEC'), ('Faço / faço parte do IBMEC HUBS', 'Faço / faço parte do IBMEC HUBS'), ('Não tenho vínculo com o IBMEC', 'Não tenho vínculo com o IBMEC')], default='Índio não ter vínculo com IBMEC', max_length=100, verbose_name='Possui vínculo com o IBMEC?'),
        ),
    ]
