# Generated by Django 5.2.7 on 2025-11-07 17:49

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_coordenador_options_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=128, region='BR', validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='grupoAlunos',
            field=models.TextField(blank=True, verbose_name='Grupo de Alunos'),
        ),
    ]
