# Generated by Django 5.2.7 on 2025-10-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_projeto_coordenador_projeto_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='projeto',
            name='proposta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastro.proposta'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='situação',
            field=models.CharField(choices=[('Em análise', 'Em análise'), ('Recusada', 'Recusada'), ('Aprovada', 'Aprovada')], default='Em análise', max_length=20),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='matricula',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='telefone',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Em andamento', max_length=50),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='telefone',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='vinculoIbmec',
            field=models.CharField(choices=[('Aluno / Ex-aluno IBMEC', 'Aluno / Ex-aluno IBMEC'), ('faço parte do IBMEC HUBS', 'faço parte do IBMEC HUBS'), ('Não tenho vínculo com o IBMEC', 'Não tenho vínculo com o IBMEC')], default='Não tenho vínculo com o IBMEC', max_length=100, verbose_name='Possui vínculo com o IBMEC?'),
        ),
    ]
