# Generated by Django 5.2.7 on 2025-11-07 18:01

import cnpj_field.models
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_empresa_cnpj_alter_empresa_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=cnpj_field.models.CNPJField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=15, region='BR', validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Telefone'),
        ),
    ]
