# Generated by Django 5.2.7 on 2025-10-31 16:47

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_coordenador_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=128, region='BR'),
        ),
    ]
