# Generated by Django 5.2.7 on 2025-10-31 17:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_proposta_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='matricula',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=128, region='BR'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=15, region='BR'),
        ),
    ]
