# Generated by Django 5.2.7 on 2025-10-31 17:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_coordenador_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=128, region='BR'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.CharField(max_length=12),
        ),
    ]
