# Generated by Django 5.2.7 on 2025-10-31 18:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_coordenador_telefone_alter_professor_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cargo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='observacoes',
            field=models.TextField(default='Nenhuma', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Número de telefone no formato internacional (ex: +5511987654321)', max_length=128, region='BR', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='É whatsapp?'),
        ),
    ]
