# Generated by Django 5.2.7 on 2025-11-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_remove_empresa_cargo_empresa_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordenador',
            table='coordenadores',
        ),
    ]
