# Generated by Django 5.2.7 on 2025-11-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_coordenador_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelTable(
            name='coordenador',
            table=None,
        ),
    ]
