# Generated by Django 5.2.7 on 2025-11-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_coordenador_options_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='situação',
            new_name='situacao',
        ),
    ]
