# Generated by Django 5.2.7 on 2025-11-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_rename_situação_proposta_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dataFim',
            field=models.DateField(verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dataInicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='situacao',
            field=models.CharField(choices=[('Em análise', 'Em análise'), ('Recusada', 'Recusada'), ('Aprovada', 'Aprovada')], default='Em análise', max_length=20, verbose_name='Situação'),
        ),
    ]
